[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.30.0"
num-complex = "0.4.6"
num-integer = "0.1.46"
png = "0.17.16"
